-- =====================================================================
-- Money Tracker — Supabase (PostgreSQL) schema + data
-- Supabase Dashboard → SQL Editor → New query → paste → Run
-- =====================================================================

begin;

-- ---------------------------------------------------------------- tables
create table if not exists public.categories (
    name            text primary key,
    monthly_budget  numeric(12,2) not null default 0 check (monthly_budget >= 0),
    sort_order      int not null default 100
);

create table if not exists public.payment_methods (
    name        text primary key,
    sort_order  int not null default 100
);

create table if not exists public.expenses (
    id              bigint generated by default as identity primary key,
    date            date not null default current_date,
    category        text not null references public.categories(name) on update cascade,
    description     text,
    amount          numeric(12,2) not null check (amount > 0),
    payment_method  text references public.payment_methods(name) on update cascade,
    created_at      timestamptz not null default now()
);

create index if not exists idx_expenses_date     on public.expenses (date desc);
create index if not exists idx_expenses_category on public.expenses (category);

-- ---------------------------------------------------------------- security
-- RLS on + no policies = public API (anon key) cannot read/write.
-- The Streamlit app connects with the database connection string, which is not affected.
alter table public.categories      enable row level security;
alter table public.payment_methods enable row level security;
alter table public.expenses        enable row level security;

-- ---------------------------------------------------------------- handy views
create or replace view public.daily_totals with (security_invoker = true) as
select date, count(*) as entries, sum(amount) as total
from public.expenses group by date order by date desc;

create or replace view public.monthly_category_totals with (security_invoker = true) as
select date_trunc('month', date)::date as month, category, count(*) as entries, sum(amount) as total
from public.expenses group by 1, 2 order by 1 desc, total desc;

-- ---------------------------------------------------------------- lookup data

insert into public.categories (name, monthly_budget, sort_order) values
    ('বাজার', 0.00, 1),
    ('খাবার / রেস্টুরেন্ট', 0.00, 2),
    ('যাতায়াত', 0.00, 3),
    ('বাইক / গাড়ি', 0.00, 4),
    ('বাসা ভাড়া', 0.00, 5),
    ('বিদ্যুৎ বিল', 0.00, 6),
    ('গ্যাস বিল', 0.00, 7),
    ('পানি বিল', 0.00, 8),
    ('ইন্টারনেট', 0.00, 9),
    ('মোবাইল রিচার্জ', 0.00, 10),
    ('চিকিৎসা / ওষুধ', 0.00, 11),
    ('শিক্ষা', 0.00, 12),
    ('কাপড় / শপিং', 0.00, 13),
    ('পরিবার', 0.00, 14),
    ('বুয়া / কাজের লোক', 0.00, 15),
    ('দাওয়াত / উপহার', 0.00, 16),
    ('দান / সদকা', 0.00, 17),
    ('কাজ / ব্যবসা', 0.00, 18),
    ('বিনোদন', 0.00, 19),
    ('অন্যান্য', 0.00, 20)
on conflict (name) do update set sort_order = excluded.sort_order;

insert into public.payment_methods (name, sort_order) values
    ('ক্যাশ', 1),
    ('বিকাশ', 2),
    ('নগদ', 3),
    ('রকেট', 4),
    ('কার্ড', 5),
    ('ব্যাংক ট্রান্সফার', 6)
on conflict (name) do update set sort_order = excluded.sort_order;

-- ---------------------------------------------------------------- your existing 13 expenses (from expenses.db)
-- Run this block only once, otherwise entries will be duplicated.
insert into public.expenses (date, category, description, amount, payment_method, created_at) values
    ('2026-10-02', 'অন্যান্য', 'Rejowan Vai', 3000.00, 'ব্যাংক ট্রান্সফার', '2026-10-08 18:17:18+00'),
    ('2026-10-03', 'খাবার / রেস্টুরেন্ট', 'Nabil Restaurant', 380.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-04', 'অন্যান্য', 'Bike Eng. Oil + Chain lop + Breakfast + lunch', 1460.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-04', 'অন্যান্য', 'Bike oil Load', 800.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-06', 'পরিবার', 'Ruku', 1000.00, 'ব্যাংক ট্রান্সফার', '2026-10-08 18:17:18+00'),
    ('2026-10-07', 'পরিবার', 'Mama', 4000.00, 'ব্যাংক ট্রান্সফার', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'পরিবার', 'Baba & Maa', 2550.00, 'ব্যাংক ট্রান্সফার', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'খাবার / রেস্টুরেন্ট', 'Chal', 1500.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'বাজার', 'Milk - 5lr', 560.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'বাজার', 'Mach', 1300.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'বাজার', 'Vegetable', 610.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'বাজার', 'Shopno Supershop', 575.00, 'ক্যাশ', '2026-10-08 18:17:18+00'),
    ('2026-10-08', 'বাজার', 'Beef', 1000.00, 'ক্যাশ', '2026-10-08 18:17:18+00');

commit;

-- ---------------------------------------------------------------- check
select count(*) as entries, sum(amount) as total from public.expenses;
